apiVersion: apps/v1
kind: Deployment
metadata:
  name: final-project-deployment
  namespace: asemmohamed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project
  template:
    metadata:
      labels:
        app: project
    spec:
      containers:
      - name: project
        image: asemmohamed321/ivolveimg:latest
        ports:
        - containerPort: 8080
