---
# tasks file for sonarqube_role
#
- name: download sonarqube binary
  shell: wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-9.9.0.65466.zip

- name: install unzip
  apt:
    name: unzip
    state: present

- name: unzip the binary package
  shell: |
    unzip sonarqube-9.9.0.65466.zip -d /opt
    mv /opt/sonarqube-9.9.0.65466 /opt/sonarqube

- name: creat sonarqube group and user
  shell: |
    groupadd sonar
    chown ubuntu:sonar /opt/sonarqube -R

- name: enable sonarqube
  shell: |
    cd /opt/sonarqube/bin/linux-x86-64
    ./sonar.sh start

